# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # box settings
    config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
    config.disksize.size = "15GB"

    # network settings
    config.vm.network "private_network", ip: "192.168.33.10"

    # folder settings
    config.vm.synced_folder ".", "/var/www/html"

    # provider settings
    #  config.vm.provider "virtualbox" do |vb|
    #    vb.memory = 1024
    #    vb.cpus = 2

    # provision settings
    config.vm.provision "shell", path: "bootstrap.sh"

#   config.vm.provision "shell", inline: <<-SHELL
#     apt-get update
#     apt-get install -y apache2
#   SHELL

end
